spring:
  datasource:
    url: "jdbc:h2:mem:mybatis-demo"
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    schema: "classpath*:db/h2/schema.sql"
    data: "classpath*:db/h2/data.sql"
  h2:
    console:
      enabled: true